### ISSUE TITLE
Add some coloring to upcoming recordings

### ISSUE THREAD

**Issue by yunosh** [hambre/Monochrome#4]
I know, it's called "Monochrome", but there already is some coloring for running recordings. I would appreciate some more coloring for other recording statuses. I like it to be able to check the upcoming recording status with a quick glance.

**Comment by hambre** [comment]
On Montag, 23. Januar 2017 00:52:45 CET Jan Schneider wrote:
> I know, it's called "Monochrome", but there already is some coloring for
> running recordings. I would appreciate some more coloring for other
> recording statuses. I like it to be able to check the upcoming recording
> status with a quick glance.

Ok, no problem. There are two more state (beside running and error) which can 
be visualized. These are warning and disabled. I have already tried some 
things and will have something ready soon.

**Comment by hambre** [comment]
Ok, i have somthing committed. Warningsares displayed with orange color, disabled recordings are displayed with a gray color instead of white.

**Comment by yunosh** [comment]
Thanks!
