### ISSUE TITLE
v31 updates

### ISSUE THREAD

**Issue by curtbinder** [hambre/Monochrome#7]
Are there any plans for updating this theme to work with v31? 
I've been using this theme for years now (and love it btw) and have noticed that at least the TV Guide doesn't work properly with v31 (Guide columns are off, no live tv miniature window, etc).

**Comment by hambre** [comment]
Am Samstag, 13. Februar 2021, 19:45:39 CET schrieb Curt Binder:
> Are there any plans for updating this theme to work with v31?
> I've been using this theme for years now (and love it btw) and have noticed
> that at least the TV Guide doesn't work properly with v31 (Guide columns
> are off, no live tv miniature window, etc).

Hi there,

the master branch does work with v31 and my assumption was that the theme
chooser in mythfrontend would use the master branch when no corresponding
other branch of a theme is available.
I just now pushed a fixes/31 branch which should be picked up by mythtv shortly
which should work with v31 automatically.
Please let me know if there are still issues left.

Ciao Jan

**Comment by curtbinder** [comment]
Thanks for the response. I will test out soon.
I just refreshed the theme list on one of my frontends and this theme is not available. My mythtv frontend is from the standard Mythbuntu PPA and it's using the fixes/v31 branch. So I have to manually install it (which is what I have done in the past to get the theme). Just thought I'd share.
I did some searching and came across this forum topic. 
https://forum.mythtv.org/viewtopic.php?t=3837
It appears to discuss and handle the situation I mentioned.

**Comment by curtbinder** [comment]
I just tested out the theme and it appears to be working good. The issues with the guide displaying I mentioned are resolved. Thank you!!!

**Comment by hambre** [comment]
Am Sonntag, 14. Februar 2021, 19:12:25 CET schrieb Curt Binder:
> I just tested out the theme and it appears to be working good. The issues
> with the guide displaying I mentioned are resolved. Thank you!!!

Great! Thanks for the feedback.

Ciao Jan
